import React from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { API_BASE_URL, authFetch } from '../api'
import { clinicDateKey, clinicDateTime, clinicTime, clinicTodayLabel } from '../lib/appointmentTime'

type Appointment = { id:number; startTime:string; endTime:string; documentationEndTime:string; status:'SCHEDULED'|'COMPLETED'|'CANCELLED'; patientName:string; patientEmail?:string; contactPhone?:string; contactAddress?:string; consultationId:number; reason?:string }
type Availability = { id:number; startDate:string; endDate:string; startTime:string; endTime:string; activeDays:number[] }
type TimeBlock = { id:number; startTime:string; endTime:string; reason?:string }
type Schedule = { availability:Availability[]; blocks:TimeBlock[] }
const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1)
const calendarDays=(month:Date)=>{const first=monthStart(month), start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
const when=clinicDateTime
const time=clinicTime

export default function DoctorAppointments(){
 const navigate=useNavigate()
 const [tab,setTab]=React.useState<'today'|'calendar'|'availability'|'blocks'>('today'), [items,setItems]=React.useState<Appointment[]>([]), [schedule,setSchedule]=React.useState<Schedule>({availability:[],blocks:[]})
 const [selected,setSelected]=React.useState<Appointment|null>(null),[loading,setLoading]=React.useState(true),[message,setMessage]=React.useState('')
 const [month,setMonth]=React.useState(()=>{const [year,month]=clinicDateKey().split('-').map(Number);return new Date(year,month-1,1)}),[selectedDate,setSelectedDate]=React.useState(()=>clinicDateKey())
 const [availabilityForm,setAvailabilityForm]=React.useState({startDate:dateKey(new Date()),endDate:dateKey(new Date()),startTime:'09:00',endTime:'17:00',activeDays:[1,2,3,4,5]})
 const [blockForm,setBlockForm]=React.useState({date:dateKey(new Date(Date.now()+86400000)),startTime:'09:00',endTime:'17:00',reason:''})
 const load=React.useCallback(async()=>{setLoading(true);try{const [a,s]=await Promise.all([authFetch(`${API_BASE_URL}/doctor/appointments`,{cache:'no-store'}),authFetch(`${API_BASE_URL}/doctor/schedule`,{cache:'no-store'})]);if(a.ok)setItems(await a.json());if(s.ok)setSchedule(await s.json())}finally{setLoading(false)}},[])
 React.useEffect(()=>{void load()},[load])
 const grouped=React.useMemo(()=>items.reduce<Record<string,Appointment[]>>((o,a)=>{(o[clinicDateKey(a.startTime)]??=[]).push(a);return o},{}),[items])
 const selectedItems=(grouped[selectedDate]||[]).sort((a,b)=>a.startTime.localeCompare(b.startTime))
 const todayKey=clinicDateKey()
 const todayItems=React.useMemo(()=>items.filter(a=>clinicDateKey(a.startTime)===todayKey&&a.status!=='CANCELLED').sort((a,b)=>a.startTime.localeCompare(b.startTime)),[items,todayKey])
 const nextAppointment=todayItems.find(a=>new Date(a.endTime).getTime()>Date.now())
 const todayQueue=nextAppointment?todayItems.filter(a=>a.id!==nextAppointment.id):todayItems
 async function request(url:string,init:RequestInit){setMessage('');const r=await authFetch(`${API_BASE_URL}${url}`,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok){let text='Unable to save changes.';try{text=(await r.json()).message||text}catch{}setMessage(text);return}setMessage('Schedule updated successfully.');await load()}
 function localInstant(date:string,value:string){return new Date(`${date}T${value}:00`).toISOString()}
 return <section className="section doctor-appointments-page">
  <div className="page-head page-head--split"><div><div className="kicker">Doctor workspace</div><h1 className="page-title">My Schedule</h1></div><button className="btn secondary" type="button" onClick={()=>navigate(-1)}>← Back</button></div>
  <nav className="doctor-schedule-tabs" aria-label="Schedule sections"><button className={tab==='today'?'is-active':''} onClick={()=>setTab('today')}>Today's Schedule</button><button className={tab==='calendar'?'is-active':''} onClick={()=>setTab('calendar')}>My Calendar</button><Link to="/doctor/consultations">Consultations</Link><button className={tab==='availability'?'is-active':''} onClick={()=>setTab('availability')}>Availability Setup</button><button className={tab==='blocks'?'is-active':''} onClick={()=>setTab('blocks')}>Leave &amp; Exceptions</button></nav>
  {message&&<div className="doctor-schedule-message" role="status">{message}</div>}{loading&&<div className="muted doctor-appointments-status">Loading schedule…</div>}
  {tab==='today'&&!loading&&<div className="doctor-today-view">
   <div className="doctor-today-heading"><div><div className="kicker">Doctor workspace</div><h2>Today's Schedule</h2></div><time dateTime={todayKey}>{clinicTodayLabel()}</time></div>
   {nextAppointment?<article className="doctor-next-card"><div className="doctor-next-copy"><div className="doctor-next-label"><span aria-hidden="true">▶</span> Next up</div><h3>{nextAppointment.patientName||'Patient'}</h3><p>{time(nextAppointment.startTime)} – {time(nextAppointment.endTime)} <span>·</span> <span className={`doctor-status doctor-status--${nextAppointment.status.toLowerCase()}`}>{nextAppointment.status}</span></p></div><div className="doctor-next-action"><strong>{appointmentCountdown(nextAppointment.startTime)}</strong><Link className="btn" to={`/doctor/consultations/${nextAppointment.consultationId}`}><span aria-hidden="true">▷</span> Start</Link></div></article>:<div className="doctor-today-empty"><strong>No more appointments today</strong><span>Your upcoming schedule is clear.</span></div>}
   <section className="doctor-today-queue"><div className="doctor-queue-heading"><h3>Today's Queue</h3><span>{todayQueue.length} remaining</span></div>{todayQueue.length===0?<p className="muted">There are no other appointments in today's queue.</p>:todayQueue.map(a=><article className="doctor-queue-row" key={a.id}><strong>{time(a.startTime)} – {time(a.endTime)}</strong><span>{a.patientName||'Patient'} · Documentation until {time(a.documentationEndTime)}</span><Link className="btn secondary" to={`/doctor/consultations/${a.consultationId}`}><span aria-hidden="true">◉</span> View</Link></article>)}</section>
  </div>}
  {tab==='calendar'&&<div className="doctor-calendar-layout"><div className="card doctor-calendar-card">
   <div className="doctor-calendar-toolbar"><button className="doctor-calendar-nav" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><div><div className="kicker">Monthly view</div><h2 className="h2 doctor-calendar-title">{month.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h2></div><button className="doctor-calendar-nav" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div>
   <div className="doctor-calendar-weekdays">{dayNames.map(d=><span key={d}>{d}</span>)}</div><div className="doctor-calendar-grid">{calendarDays(month).map(d=>{const key=dateKey(d),count=grouped[key]?.length||0,blocked=schedule.blocks.some(b=>key>=b.startTime.slice(0,10)&&key<=b.endTime.slice(0,10));return <button key={key} className={['doctor-calendar-day',count?'has-appointments':'',blocked?'is-blocked':'',key===selectedDate?'is-selected':'',key===todayKey?'is-today':'',d.getMonth()!==month.getMonth()?'is-muted':''].filter(Boolean).join(' ')} onClick={()=>setSelectedDate(key)}><span className="doctor-calendar-date-number">{d.getDate()}</span>{count>0&&<span className="doctor-calendar-badge">{count}</span>}{blocked&&<small>Blocked</small>}</button>})}</div>
  </div><aside className="card doctor-day-panel"><div className="doctor-day-panel-head"><div><div className="kicker">Selected date</div><h2 className="h3">{new Date(`${selectedDate}T00:00`).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</h2></div><span className="doctor-day-count">{selectedItems.length} appointment{selectedItems.length===1?'':'s'}</span></div>{!selectedItems.length?<div className="muted doctor-empty-day">No appointments scheduled for this date.</div>:<div className="doctor-appointment-list">{selectedItems.map(a=><article className="doctor-appointment-item" key={a.id}><div className="doctor-appointment-time">{time(a.startTime)}</div><div className="doctor-appointment-summary"><strong>{a.patientName||'Patient'}</strong><span>Consultation #{a.consultationId}</span><span className={`doctor-status doctor-status--${a.status.toLowerCase()}`}>{a.status}</span></div><button className="btn secondary doctor-view-details" onClick={()=>setSelected(a)}>View details</button></article>)}</div>}</aside></div>}
  {tab==='availability'&&<div className="doctor-management-grid"><form className="card doctor-schedule-form" onSubmit={e=>{e.preventDefault();void request('/doctor/schedule/availability',{method:'POST',body:JSON.stringify(availabilityForm)})}}><h2 className="h3">New availability</h2><div className="doctor-form-grid"><label>From<input type="date" value={availabilityForm.startDate} onChange={e=>setAvailabilityForm({...availabilityForm,startDate:e.target.value})}/></label><label>To<input type="date" value={availabilityForm.endDate} onChange={e=>setAvailabilityForm({...availabilityForm,endDate:e.target.value})}/></label><label>Opens at<input type="time" step="600" value={availabilityForm.startTime} onChange={e=>setAvailabilityForm({...availabilityForm,startTime:e.target.value})}/></label><label>Closes at<input type="time" step="600" value={availabilityForm.endTime} onChange={e=>setAvailabilityForm({...availabilityForm,endTime:e.target.value})}/></label></div><fieldset><legend>Active days</legend><div className="doctor-day-chips">{dayNames.map((d,i)=><button type="button" key={d} className={availabilityForm.activeDays.includes(i+1)?'is-active':''} onClick={()=>setAvailabilityForm({...availabilityForm,activeDays:availabilityForm.activeDays.includes(i+1)?availabilityForm.activeDays.filter(x=>x!==i+1):[...availabilityForm.activeDays,i+1]})}>{d}</button>)}</div></fieldset><button className="btn" type="submit">Save availability</button></form><ScheduleList title="Active schedules" empty="No availability configured. The existing 09:00–17:00 clinic schedule remains active." rows={schedule.availability.map(a=>({id:a.id,title:`${a.startDate} – ${a.endDate}`,detail:`${a.startTime.slice(0,5)} – ${a.endTime.slice(0,5)} · ${a.activeDays.map(d=>dayNames[d-1]).join(', ')}`}))} onDelete={id=>request(`/doctor/schedule/availability/${id}`,{method:'DELETE'})}/></div>}
  {tab==='blocks'&&<div className="doctor-management-grid"><form className="card doctor-schedule-form" onSubmit={e=>{e.preventDefault();void request('/doctor/schedule/blocks',{method:'POST',body:JSON.stringify({startTime:localInstant(blockForm.date,blockForm.startTime),endTime:localInstant(blockForm.date,blockForm.endTime),reason:blockForm.reason})})}}><h2 className="h3">Block time</h2><p className="muted">Add leave, training or another exception. Periods containing appointments cannot be blocked.</p><div className="doctor-form-grid"><label>Date<input type="date" value={blockForm.date} onChange={e=>setBlockForm({...blockForm,date:e.target.value})}/></label><span/><label>From<input type="time" value={blockForm.startTime} onChange={e=>setBlockForm({...blockForm,startTime:e.target.value})}/></label><label>To<input type="time" value={blockForm.endTime} onChange={e=>setBlockForm({...blockForm,endTime:e.target.value})}/></label></div><label>Reason (optional)<input value={blockForm.reason} maxLength={255} placeholder="Conference, annual leave…" onChange={e=>setBlockForm({...blockForm,reason:e.target.value})}/></label><button className="btn" type="submit">Block selected time</button></form><ScheduleList title="Leave & exceptions" empty="No blocked periods." rows={schedule.blocks.map(b=>({id:b.id,title:`${when(b.startTime)} – ${time(b.endTime)}`,detail:b.reason||'No reason provided'}))} onDelete={id=>request(`/doctor/schedule/blocks/${id}`,{method:'DELETE'})}/></div>}
  {selected&&<div className="card doctor-appointment-details"><div className="page-head page-head--split doctor-detail-head"><h2 className="h3">Appointment Details</h2><button className="btn secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="doctor-detail-grid"><div><strong>Patient:</strong> {selected.patientName}</div><div><strong>Date/time:</strong> {when(selected.startTime)} – {time(selected.endTime)} · Documentation reserved until {time(selected.documentationEndTime)}</div><div><strong>Status:</strong> {selected.status}</div><div><strong>Consultation:</strong> <Link to={`/doctor/consultations/${selected.consultationId}`}>#{selected.consultationId}</Link></div><div><strong>Reason/details:</strong> {selected.reason||'—'}</div><div><strong>Contact:</strong> {[selected.contactPhone,selected.patientEmail,selected.contactAddress].filter(Boolean).join(' • ')||'—'}</div></div></div>}
 </section>
}
function appointmentCountdown(startTime:string){const minutes=Math.ceil((new Date(startTime).getTime()-Date.now())/60000);if(minutes<=0)return 'Ready now';if(minutes<60)return `in ${minutes} min`;const hours=Math.floor(minutes/60),remainder=minutes%60;return `in ${hours}h${remainder?` ${remainder}m`:''}`}
function ScheduleList({title,empty,rows,onDelete}:{title:string;empty:string;rows:{id:number;title:string;detail:string}[];onDelete:(id:number)=>void}){return <div className="card doctor-schedule-list"><div className="doctor-list-heading"><h2 className="h3">{title}</h2><span>{rows.length} entries</span></div>{!rows.length?<p className="muted">{empty}</p>:rows.map(r=><div className="doctor-schedule-row" key={r.id}><div><strong>{r.title}</strong><span>{r.detail}</span></div><button className="btn secondary" onClick={()=>onDelete(r.id)}>Remove</button></div>)}</div>}
