// src/screens/ReferralView.tsx — read-only referral letter access
import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { authFetch, API_BASE_URL, resolveApiUrl, openAuthenticatedFile } from '../api'
import { usePatient } from '../state/patient'

export default function ReferralView() {
  const navigate = useNavigate()
  const { activePatient, loading: patientLoading, queryString } = usePatient()
  const [pdfUrl, setPdfUrl] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [opening, setOpening] = useState(false)
  const [openErr, setOpenErr] = useState<string | null>(null)

  async function openPdf() {
    if (!pdfUrl) return
    setOpening(true)
    setOpenErr(null)
    try {
      await openAuthenticatedFile(pdfUrl)
    } catch (e: any) {
      setOpenErr(e?.message || 'Unable to open the PDF.')
    } finally {
      setOpening(false)
    }
  }

  useEffect(() => {
    if (patientLoading || !activePatient) return
    let alive = true
    setLoading(true)
    ;(async () => {
      try {
        const res = await authFetch(`${API_BASE_URL}/referrals/latest?${queryString}`, { cache: 'no-store' })
        if (!alive) return
        if (!res.ok || res.status === 204) { setPdfUrl(null); return }
        const j = await res.json().catch(() => null)
        setPdfUrl(j?.pdfUrl ? resolveApiUrl(API_BASE_URL, j.pdfUrl) : null)
      } catch {
        if (alive) setPdfUrl(null)
      } finally {
        if (alive) setLoading(false)
      }
    })()
    return () => { alive = false }
  }, [activePatient, patientLoading, queryString])

  return (
    <>
      <div className="page-head">
        <div>
          <div className="page-title">Referral Letter</div>
          <div className="page-sub">{activePatient?.name || ''}</div>
        </div>
        <button type="button" className="bs" onClick={() => navigate(-1)}>‹ Back</button>
      </div>

      {loading || patientLoading ? (
        <div className="card">Loading…</div>
      ) : !pdfUrl ? (
        <div className="card" style={{ textAlign: 'center', color: 'var(--text-muted)' }}>
          No referral letter has been generated for {activePatient?.name || 'this traveller'} yet.
        </div>
      ) : (
        <div className="card">
          <div className="notice n-info">
            <i className="ti ti-file-text" aria-hidden="true" />
            Your referral letter has been generated by your clinician. Download it below to view the full details.
          </div>
          <button type="button" className="bp" onClick={openPdf} disabled={opening}>
            <i className="ti ti-download" aria-hidden="true" /> {opening ? 'Opening…' : 'Download Referral Letter'}
          </button>
          {openErr && <div className="notice n-warn" style={{ marginTop: 10 }}><i className="ti ti-alert-triangle" aria-hidden="true" />{openErr}</div>}
        </div>
      )}

      <Link to={queryString ? `/care-history?${queryString}` : '/care-history'} className="bs" style={{ marginTop: 8, display: 'inline-flex' }}>
        View Care History
      </Link>
    </>
  )
}
