server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
  tomcat:
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/godwitcare
    username: godwitcare_user
    password: godwitcare_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration/h2
    baseline-on-migrate: true
    validate-on-migrate: false
  logging:
    level:
      org.hibernate.SQL: INFO
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:}
  auth:
    token: ${TWILIO_AUTH_TOKEN:}
  whatsapp:
    from: ${TWILIO_WHATSAPP_FROM:}

otp:
  expiry-seconds: ${OTP_EXPIRY_SECONDS:300}

